# Travis-CI config for https://github.com/hpc-carpentry/hpc-intro
# Results at https://travis-ci.org/github/hpc-carpentry/hpc-intro

dist: xenial
language: python
python: 3.7

branches:
  only:
  - gh-pages
  - /.*/

before_install:
install:
script:

jobs:
  include:
    - stage: "Check for typos and spelling mistakes"
      before_install: # Don't need everything to build the site
      install:
        pip install codespell
      script:
        codespell --skip="assets,*.svg,bin" --quiet-level=2  -L "rouge,dropse,namd,hist"
    - stage: "Build the site"
      before_install: 
        - sudo apt-get update -y
        - rvm default
        - gem install bundler jekyll json kramdown
        - bundle config build.nokogiri --use-system-libraries
        - bundle install
      install:
        pip install pyyaml
      script:
        - make lesson-check-all
        - make --always-make site

