# HPC-Intro Jekyll configuration
---

#------------------------------------------------------------
# SITE specific configuration
#------------------------------------------------------------

# Cluster host and scheduler options: the defaults come from
# the HPC Carpentry tutorial cluster, running Slurm. Other
# options can be found in the library of snippets,
# `_includes/snippets_library`. To use one, replace options
# below with those in `_config_options.yml` from the
# library. E.g, to customise for Cirrus at EPCC, running
# Slurm, we could replace the options below with those from
# 
# _includes/snippets_library/EPCC_Cirrus_slurm/_config_options.yml
# 
# If your cluster is not represented in the library, please
# copy an existing folder, rename it, and customize for your
# installation. Remember to keep the leading slash on the
# `snippets` variable below!

# ---------------------------------------------------------------
# HPC Carpentries in the Cloud: Slurm + Software Stack from EESSI
# ---------------------------------------------------------------
#
# The HPC Carpentry Cluster in the Cloud is provided as a public
# service by volunteers. It is provisioned with Magic Castle
# <https://github.com/ComputeCanada/magic_castle> using the EESSI
# <https://eessi.github.io/docs/> software stack. If you need an
# account, please visit <cluster.hpc-carpentry.org>.
#
# Compute responsibly.

snippets: "/snippets_library/HPCC_MagicCastle_slurm"

local:
  prompt: "[you@laptop:~]$"
  bash_shebang: "#!/usr/bin/env bash"

remote:
  name: "HPC Carpentry's Cloud Cluster"
  login: "cluster.hpc-carpentry.org"
  portal: "https://mokey.cluster.hpc-carpentry.org"
  host: "login1"
  node: "node1"
  location: "cluster.hpc-carpentry.org"
  homedir: "/home"
  user: "yourUsername"
  module_python3: "Python"
  prompt: "[yourUsername@login1 ~]$"
  bash_shebang: "#!/bin/bash"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: ""
  queue:
    debug: "smnode"
    testing: "cpubase_bycore_b1"
  status: "squeue"
  flag:
    user: "-u yourUsername"
    interactive: ""
    histdetail: "-l -j"
    name: "-J"
    time: "-t"
    queue: "-p"
    nodes: "-N"
    tasks: "-n"
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u yourUsername"
  hist_filter: ""

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 15-modules
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility

#------------------------------------------------------------
# Values for this lesson
#------------------------------------------------------------

# Which carpentry is this?
# "swc": Software Carpentry
# "dc":  Data Carpentry
# "lc":  Library Carpentry
# "cp":  Carpentries (e.g., instructor training)
carpentry: "incubator"

# Overall title for pages.
title: "Introduction to High-Performance Computing"

# Email address, no mailto:
email: "team@carpentries.org"

# Life cycle stage of the lesson ("pre-alpha", "alpha", "beta", "stable")?
life_cycle: "alpha"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Magic to make URLs resolve both locally and on GitHub. Please don't change.
repository: <USERNAME>/<PROJECT>

# Invoke the Carpentries theme rather than copying into our repository.
remote_theme: carpentries/carpentries-theme

# Sites.
amy_site: "https://amy.carpentries.org/"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Specify that things in the Episodes and Extras collections should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/

# Turn on built-in syntax highlighting.
highlighter: rouge

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
